version: "3.9"
services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - 9000:9000
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
        container_name: react_frontend
        ports:
            - 3000:3000
        stdin_open: true
        tty: true

    db:
        image: postgres:17
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: pfa2
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mimi
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
