<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{- escapeXML ( index . 0 ).Target }} - Trivy Report - {{ now }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f7f9fc;
            color: #333;
        }
        h1, h2 {
            text-align: center;
        }
        .summary {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-bottom: 30px;
        }
        .summary-card {
            background-color: white;
            padding: 15px 25px;
            border-radius: 8px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.1);
            text-align: center;
        }
        .summary-card h3 {
            margin: 0;
            font-size: 1.2em;
        }
        .summary-card p {
            margin: 5px 0 0;
            font-size: 1.5em;
            font-weight: bold;
        }
        table {
            width: 90%;
            margin: 0 auto;
            border-collapse: collapse;
            background-color: white;
            box-shadow: 0 2px 6px rgba(0,0,0,0.1);
        }
        th, td {
            padding: 10px;
            border: 1px solid #ddd;
            text-align: left;
        }
        th {
            background-color: #4a6fa5;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .severity {
            font-weight: bold;
            color: #fff;
            padding: 4px 8px;
            border-radius: 4px;
        }
        .LOW { background-color: #5fbb31; }
        .MEDIUM { background-color: #e9c600; }
        .HIGH { background-color: #ff8800; }
        .CRITICAL { background-color: #e40000; }
        .UNKNOWN { background-color: #747474; }
        .links a { display: block; font-size: 0.9em; }
        footer {
            text-align: center;
            margin-top: 40px;
            font-size: 0.85em;
            color: #777;
        }
    </style>
</head>
<body>
<h1>{{- escapeXML ( index . 0 ).Target }} - Trivy Report</h1>
<h2>{{ now }}</h2>

<div class="summary">
    <div class="summary-card">
        <h3>LOW</h3>
        <p>{{ countSeverities . "LOW" }}</p>
    </div>
    <div class="summary-card">
        <h3>MEDIUM</h3>
        <p>{{ countSeverities . "MEDIUM" }}</p>
    </div>
    <div class="summary-card">
        <h3>HIGH</h3>
        <p>{{ countSeverities . "HIGH" }}</p>
    </div>
    <div class="summary-card">
        <h3>CRITICAL</h3>
        <p>{{ countSeverities . "CRITICAL" }}</p>
    </div>
</div>

<table>
    <tr>
        <th>Package</th>
        <th>Vulnerability ID</th>
        <th>Severity</th>
        <th>Installed Version</th>
        <th>Fixed Version</th>
        <th>Links</th>
    </tr>
    {{- range . }}
    {{- range .Vulnerabilities }}
    <tr>
        <td>{{ escapeXML .PkgName }}</td>
        <td>{{ escapeXML .VulnerabilityID }}</td>
        <td><span class="severity {{ escapeXML .Vulnerability.Severity }}">{{ escapeXML .Vulnerability.Severity }}</span></td>
        <td>{{ escapeXML .InstalledVersion }}</td>
        <td>{{ escapeXML .FixedVersion }}</td>
        <td class="links">
            {{- range .Vulnerability.References }}
            <a href={{ escapeXML . | printf "%q" }} target="_blank">{{ escapeXML . }}</a>
            {{- end }}
        </td>
    </tr>
    {{- end }}
    {{- end }}
</table>

<footer>
    Generated by Trivy - Powered Report Template
</footer>
</body>
</html>
