apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-server
  template:
    metadata:
      labels:
        app: rasa-server
    spec:
      containers:
        - name: rasa
          image: pfa2-rasa-server:latest
          ports:
            - containerPort: 5005
          volumeMounts:
            - mountPath: /app
              name: rasa-volume
      volumes:
        - name: rasa-volume
          emptyDir: {}  # Or a PersistentVolumeClaim if needed
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-service
spec:
  selector:
    app: rasa-server
  ports:
    - port: 80
      targetPort: 5005
  type: ClusterIP
